### ISSUE TITLE
Console Task terminated

### ISSUE THREAD

**Issue by designpilot** [ErdmannFreunde/euf_hero#1]
Hallo Dennis

Wenn ich die euf_hero über den CTM installieren möchte bekomm ich folgende Meldung:

`Could not find a version of package erdmannfreunde/euf_hero matching your m  
  inimum-stability (stable). Require it with an explicit version constraint a  
  llowing its desired stability.`

wenn ich die composer.json bearbeite, was muss ich da genau eintragen ???? Laut Packagist
ist die euf_hero immer noch dev-develop Status.

Müsste der Eintrag dann in der composer.json dann nicht so aussehen:
"erdmannfreunde/euf_hero": "^dev-develop"

**Comment by denniserdmann** [comment]
Genau, solange das Theme noch nicht fertig ist, ist auch die Extension noch nicht offiziell fertig. Aber mit `"erdmannfreunde/euf_hero": "dev-develop"` kannst du die develop-Version testen.
