### ISSUE TITLE
Contao 5.3 kompatibel?

### ISSUE THREAD

**Issue by sgn-dev** [ErdmannFreunde/euf_hero#5]
Moin zusammen, habe gerade versucht das ganze in Contao 5.3 zu installieren - leider ohne Erfolg. In eurem Sirius Theme wird euf_hero aber doch weiter verwendet oder? Habt ihr mir einen Tip wie ich das zum Laufen bekomme?

Herzlichen Dank im Voraus :)

**Comment by denniserdmann** [comment]
Es gibt ein neues Hero-Element, das unter Contao 5 zum Einsatz kommt: https://github.com/nutshell-framework/hero-element
